url: https://y7kim.github.io
baseurl: /home/

# Site settings
title: Elections.no
email: psmaas@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Patricia Aas
  pic: patricia
  position: Editor
  social:
    - title: twitter
      url: https://twitter.com/pati_gallardo
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

#- name: Larry Parker
#  pic: 2
#  position: Lead Marketer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #

#- name: Diana Petersen
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/elections_no
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url:
#  - title: bitbucket
#    url:
  - title: github
    url: http://github.com/elections-no

# Postal address (add as many lines as necessary)
address:
  - line:

# Build settings
markdown: kramdown
permalink: pretty